format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nodejs\
$custom\
$line_break\
$character"""

[nodejs]
symbol = "[⬢](bold green) "

[package]
disabled = true

[docker_context]
disabled = true%